name = "dx7sport"
compatibility_date = "2025-05-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
# DATABASE_URL should be set in the Cloudflare Dashboard
# GOOGLE_AI_API_KEY should be set in the Cloudflare Dashboard
