/**
 * Telegram Bot Integration
 * Sends notifications when a new article draft is generated by the Ghost Reporter.
 */

export async function sendTelegramAlert(title: string, articleId: number): Promise<void> {
  const token = process.env.TELEGRAM_BOT_TOKEN;
  const chatId = process.env.TELEGRAM_CHAT_ID;

  if (!token || !chatId) {
    console.warn('[Telegram] Skip alert: TELEGRAM_BOT_TOKEN or TELEGRAM_CHAT_ID not configured.');
    return;
  }

  const reviewUrl = `https://dx7sport.com/admin/article/${articleId}`;
  
  const text = `🚨 *New Draft Ready!* 🚨\n\n` +
               `📝 *Title:* ${title}\n\n` +
               `🔗 *Review & Publish:* [Click Here to Review](${reviewUrl})`;

  try {
    const res = await fetch(`https://api.telegram.org/bot${token}/sendMessage`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        chat_id: chatId,
        text: text,
        parse_mode: 'Markdown',
        disable_web_page_preview: false,
      }),
    });

    if (!res.ok) {
      const errorData = await res.json();
      console.error('[Telegram] API Error:', errorData);
    } else {
      console.log('[Telegram] Alert sent successfully.');
    }
  } catch (err) {
    console.error('[Telegram] Failed to send alert:', err);
  }
}
